### ISSUE TITLE
Tapi restart line monitor

### ISSUE THREAD

**Issue by amirhp** [markjulmar/atapi.net#14]
We have a problem with our network and Panasonic tapi service provider status become disconnected is there a way to detect that and re register the lines?

**Comment by vfabregat** [comment]
@amirhp I don't know what problem are you having, but to know the line statuses I use two kinds of events coming from Tapi `TapiManager`:

- `LineAdded`, `LineRemoved`: To know when a line was added or removed, in this case, I add an event listener to check the event from the new line (such as: `NewCall`, etc)
- `LineChanged`: Maybe this could help you. This event has a `Change` property which indicates the change that fired the event. And also you can check the property on the line `Status.InService`.

I hope that this information helps you to fix your issue.

Regards.

**Comment by markjulmar** [comment]
Try contacting Panasonic and see if they have an updated TSP which reports line disconnects (it's in the specification as noted above). If not, perhaps try doing a `lineShutdown` periodically followed by a `lineInitialize` to force the TSP to reset locally. It's not a great solution, but it might work..
