### ISSUE TITLE
Metadata file could not be found

### ISSUE THREAD

**Issue by harmoniemand** [markjulmar/atapi.net#15]
![image](https://user-images.githubusercontent.com/706739/38309520-8f55f5d4-381a-11e8-91cb-0e189db8efd9.png)

This error occurs if I try to run your demos. Is there anything I need to do before running?

**Comment by portison** [comment]
I've not seen the demos myself, but that error is Visual Studio being unable to find the Atapi assembly at the location show in your screen-print.  Make sure you've built the Atapi project as x64 Debug and that the x64 debug configuration  is set to write to your location (....src/src/bin/x64/Debug).  It might be quicker and easier to delete your references to ATAPI in the demo projects, creating the references again and then rebuilding.

**Comment by vfabregat** [comment]
@harmoniemand I can't reproduce the error, did you try the portison suggestion?
