### ISSUE TITLE
TapiVersion enum is missing the value for V22

### ISSUE THREAD

**Issue by cremor** [markjulmar/atapi.net#17]
Originally reported as CodePlex issue #13316 and still relevant for the new version:

`TapiLine.NegotiatedVersion` returns 0x20002 for me, which should be present in the `TapiVersion` enum as `V22`.

More information: https://msdn.microsoft.com/en-us/library/ms737251(v=vs.85).aspx

**Comment by vfabregat** [comment]
@cremor this is merged. Only pending to be published in nuget.

@markjulmar  do you have any plan to release a new version in nuget?

regards.

**Comment by markjulmar** [comment]
Sure, I can -- let me see if I can do that this weekend.
