### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by sadeghrz** [markjulmar/atapi.net#2]
hi men
i have a panasonic ns500 pbx device .
i searching in internet for a while and now know i need a tapi application to connect to my pbx to manage phone and calls.
but it still confusing for me!
can you please tell me how i can connect to my pbx and programing for it? can i use your library for it?
i just need some clear road map and knowlege. 
Thank you a lot!

**Comment by markjulmar** [comment]
TAPI requires a special Windows device driver called a "TAPI Service Provider" to work with a device. Panasonic has to provide this device driver in order for you to use TAPI. I'm not sure if there is one out there - contact Panasonic and find out. If there is, you can download/install it and _then_ you could use something like this library.

**Comment by portison** [comment]
I have been involved in writing C# software that has uses the ATAPI library and which has been used to integrate with a Panasonic KX PBX for third-party TAPI call monitoring.

I am not at all familiar with Panasonic phone systems. We always use partners who are phone system experts to provide or order licensed copies of TSPs and to configure the PBXs to support TAPI.

A Google search suggests that the NS500 supports TAPI 2.1. If this is indeed the case then, and as suggested in the post by @markjulmar , I recommend that you talk to your phone system maintainer or Panasonic themselves to find out how to order or download the TSP (TAPI Service Provider). I also recommend that you find out if the Panasonic PBX requires any licenses to enable TAPI. I can tell you that the TSP our partner installed on our CTI server was called the "Panasonic TAPI Service Provider". 

The ATAPI library makes TAPI programming in .net pretty easy, but I feel I should warn you that you will need a good grasp of Microsoft TAPI and the events it will generate to get the most out of it. If you are a .net developer then I can thoroughly recommend ATAPI over grafting away in native c/c++ which is how I used to do my TAPI programming 20 years ago.
