### ISSUE TITLE
NuGet package no longer targets .NET 4.0

### ISSUE THREAD

**Issue by mrutter** [markjulmar/atapi.net#23]
Hello.

I'm trying to update ATAPI from v. 2013.1.4 to last stable 2018.3.9 but I get an error about the target .NET framework (in my project, I'm still using .NET 4.0). Following is the error:

`Could not install package 'ATAPI 2018.3.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I see that currently you're targeting .NET 4.6. Please can you confirm me that ATAPI requires at least .NET 4.6? If not, is it possible to target also previous versions (and .NET 4.0 in particular)?

Thank you.

**Comment by markjulmar** [comment]
The package is set for VS2017 and 4.6, but you can grab the source and build it yourself - there might be a few things you'll have to change to make it compatible with 4.0; but it should be doable. If you do recompile it - use `#if` markers to change the code and submit a PR, maybe we can multi-target the package...

**Comment by mrutter** [comment]
Ok Mark,
thank you for letting me know. I will go in deep in the next weeks.
