### ISSUE TITLE
Error compiling - Cryptographic failure --Error signing assembly-- CS1548

### ISSUE THREAD

**Issue by uribes78** [markjulmar/atapi.net#27]
I have already clone the repo, and using SharpDevelop to test the Phone.Net app, but I got an error about the sign. Is there a change about it or Am I missing something to compile the Atapi.dll?

Hope you can help me, I want to test it. Thanks

**Comment by markjulmar** [comment]
You will need to provide your own signing cert, or turn that off in the settings.
