### ISSUE TITLE
tapiManager.Initialize() is alwayse false!

### ISSUE THREAD

**Issue by sadeghrz** [markjulmar/atapi.net#3]
hi men.
as you told me in past issues i install tsp and connected it to my panasonic kx-ns500 pbx.
its seems connected succesfully and have send and recieve data in tsp monitor.
but when i run your test projects (Tcmon and phone) tapiManager.Initialize() is allwayse false.
i cant find any part of your code that you set ip and port of pbx. how can i config your test project to run on my pbx?

thank you.

**Comment by markjulmar** [comment]
Setup has to happen in the TSP - not in TAPI. 

TAPI has no options for setting up the connection between the device driver (TSP) and the device. My guess is there's a configuration file or dialog somewhere as part of the TSP setup.

Once you do that, Initialize should return the # of lines available.

**Comment by sadeghrz** [comment]
Tsp seems ok, tsp show me ok connection status and send/recieve between pc and bpx, whats wrong?

**Comment by markjulmar** [comment]
No idea. All I can tell you is once it's setup properly, TAPI will show visible lines. There's no configuration on the API side.

**Comment by portison** [comment]
I'm assuming when you say fail, that you mean tapiManager.Initilize() returns false.

Even if your Panasonic tsp isn't configured correctly, the tapiManager.Initialize() should not fail (it just wouldn't have visibility of any Panasonic tapi lines).

I've only seen tapi initialisation fail (returning false in ATAPI) if the telephony service isn't running. Try checking the telephony service is running on the dev machine with the tsp installed on it.

Sometimes people disable the Telephony service or very occasionally it fails.

There's an Microsoft application called TAPI browser that is widely used to test and learn about TAPI. You could download it and use it in this instance to prove that TAPI initialisation isn't just failing in the ATAPI library (it almost certainly won't be).
