### ISSUE TITLE
Can't find phones  in a line.

### ISSUE THREAD

**Issue by dev-sr427** [markjulmar/atapi.net#30]
... ... 
int numLines = InitializeLineDevices();
int numPhones = InitializePhoneDevices();
... ...

above, one line has more than one phone.
But the "numPhones = 0" , why?
I'd like to know the reason. And when incoming call, the called id is line's id.
I wanna know the exact phone number, not line id.
I wish your help. Thank you!

**Comment by markjulmar** [comment]
Try testing with the Tapi Browser in the Windows SDK. The library is reporting what TAPI tells it -- which is what the driver is telling TAPI. My guess is you don't have the right drivers installed for your hardware, or the manufacturer isn't providing phone support - only line (which is very common).
