### ISSUE TITLE
TapiCall id error

### ISSUE THREAD

**Issue by avsone** [markjulmar/atapi.net#5]
We use our  monitor functionality program in  several computers. Sometime we have got next  situation with incomming  call in OnCallStateChanged  - 
We have no event with final CallState.
But  we have got Call  with Id+1(maybe 2 or 3) and CallOrigin =Unknown and  CallState = Connected.

**Comment by vfabregat** [comment]
Hi @avsone which `CallState` are you expecting as "Final"

**Comment by avsone** [comment]
Hi Victor,
I have found the reason of this error. It is not relative to this project.  It is an error in driver's TAPI implementation. Driver can divide one call to several calls with several ids.

**Comment by vfabregat** [comment]
@markjulmar @avsone this issue could be closed right?

**Comment by markjulmar** [comment]
Resolved with PR #10
