### ISSUE TITLE
Shutdown fails, if Initialize fails because of no lines and no phones

### ISSUE THREAD

**Issue by flensrocker** [markjulmar/atapi.net#7]
`Shutdown` wants to join the `_workerThread`, but this thread has never been started, if there are no lines and no phones.

Maybe `_workerThread.ThreadState` should be tested on `ThreadState.Unstarted`. Otherwise there is a `ThreadStateException` in `Dispose` or if I explicitly `Shutdown` the `TapiManager` on app-shutdown.

**Comment by markjulmar** [comment]
Maybe we could change the code to not even create the thread (or stop it and `null` it out) in `Initialize` if no lines are detected. Then we could just test for `null` in `Shutdown`. That would be simple and elegant. Want to do a PR?

**Comment by flensrocker** [comment]
Yes, I will prepare a PR.
