### ISSUE TITLE
Compilation error with Visual Studio 2017

### ISSUE THREAD

**Issue by flensrocker** [markjulmar/atapi.net#9]
```
D:\src\atapi.net\src\src\Events.cs(374,20,374,29): error CS0266: Cannot implicitly convert type 'JulMar.Atapi.ITapiLine' to 'JulMar.Atapi.TapiLine'. An explicit conversion exists (are you missing a cast?)
D:\src\atapi.net\src\src\TapiManager.cs(547,39,547,55): error CS1061: 'ITapiLine' does not contain a definition for 'OnDeviceSpecific' and no extension method 'OnDeviceSpecific' accepting a first argument of type 'ITapiLine' could be found (are you missing a using directive or an assembly reference?)
```
There are different ways to resolve them:
1. changing the type to `ITapiLine` and adding `OnDeviceSpecific` to the interface
2. explicit cast to `TapiLine`

I don't know which way is preferred. I will post diffs for both possibilities.

[issue-9-extend-itapiline.txt](https://github.com/markjulmar/atapi.net/files/1743572/issue-9-extend-itapiline.txt)
[issue-9-explicit-cast.txt](https://github.com/markjulmar/atapi.net/files/1743576/issue-9-explicit-cast.txt)

**Comment by markjulmar** [comment]
This was introduced in a PR from @vfabregat - Victor, can you suggest which way you'd like to see this addressed? Thanks!

**Comment by vfabregat** [comment]
Oh! I'm so sorry about this. I'll fix shortly
